spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    inetutils:
      default-hostname: localhost
      default-ip-address: 127.0.0.1
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888

